---
- include: rhel.yml
  when: ansible_os_family == 'RedHat'

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Ensure wheel group exists
  group: name=wheel state=present system=yes

- name: Setup wheel group sudo perms
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create stack user
  user:
    name: stack
    state: present
    groups: wheel
    shell: /bin/bash

- name: Clone devstack
  sudo: true
  sudo_user: stack
  git:
    repo: 'https://git.openstack.org/openstack-dev/devstack'
    dest: '~/devstack'

- name: Set up local.conf
  sudo: true
  sudo_user: stack
  template:
    src: local.conf.j2
    dest: '~/devstack/local.conf'

- name: Run the stack.sh script
  sudo: true
  sudo_user: stack
  shell: "./stack.sh 2>&1 | tee stack_run.log"
  args:
    chdir: '~/devstack'
