---
- name: Install prerequisite system packages
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: true
  with_items:
    - git
    - build-essential
    - python-dev
    - python-setuptools

- name: Run get-pip.py
  shell: curl https://bootstrap.pypa.io/get-pip.py | python
